=== josh/wikidata-api-schemas/lexeme.schema.json
{
  "$id": "https://josh.github.io/wikidata-api-schemas/lexeme.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lexeme",
  "type": "object",
  "properties": {
    "type": {
      "description": "The entity type identifier",
      "type": "string",
      "const": "lexeme"
    },
    "pageid": { "$ref": "./entity.schema.json#/$defs/pageid" },
    "ns": { "$ref": "./entity.schema.json#/$defs/ns", "const": 146 },
    "title": { "$ref": "./entity.schema.json#/$defs/title" },
    "lastrevid": { "$ref": "./entity.schema.json#/$defs/lastrevid" },
    "modified": { "$ref": "./entity.schema.json#/$defs/modified" },
    "id": { "$ref": "#/$defs/id" },
    "lemmas": {
      "title": "Lemmas",
      "$ref": "./multilingual-text-value.schema.json#/$defs/values",
      "type": "object",
      "minProperties": 1
    },
    "lexicalCategory": { "$ref": "./item.schema.json#/$defs/id" },
    "language": { "$ref": "./item.schema.json#/$defs/id" },
    "claims": { "$ref": "./statement.schema.json#/$defs/group" },
    "forms": {
      "oneOf": [
        { "type": "object", "const": {}, "maxProperties": 0 },
        {
          "type": "array",
          "items": { "$ref": "./form.schema.json" },
          "minItems": 0
        }
      ]
    },
    "senses": {
      "oneOf": [
        { "type": "object", "const": {}, "maxProperties": 0 },
        {
          "type": "array",
          "items": { "$ref": "./sense.schema.json" },
          "minItems": 0
        }
      ]
    }
  },
  "required": [
    "pageid",
    "ns",
    "title",
    "lastrevid",
    "modified",
    "type",
    "id",
    "lemmas",
    "lexicalCategory",
    "language",
    "claims",
    "forms",
    "senses"
  ],
  "additionalProperties": false,
  "$defs": {
    "id": {
      "$anchor": "id",
      "title": "Lexeme ID",
      "type": "string",
      "minLength": 2,
      "pattern": "^L[1-9][0-9]*$"
    }
  }
}

=== josh/wikidata-api-schemas/test/lexeme/pass/L4.json
{
  "type": "lexeme",
  "id": "L4",
  "lemmas": { "en": { "language": "en", "value": "windsurf" } },
  "lexicalCategory": "Q24905",
  "language": "Q1860",
  "claims": {
    "P5238": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5238",
          "datavalue": {
            "value": {
              "entity-type": "lexeme",
              "numeric-id": 3324,
              "id": "L3324"
            },
            "type": "wikibase-entityid"
          },
          "datatype": "wikibase-lexeme"
        },
        "type": "statement",
        "qualifiers": {
          "P1545": [
            {
              "snaktype": "value",
              "property": "P1545",
              "hash": "2a1ced1dca90648ea7e306acbadd74fc81a10722",
              "datavalue": { "value": "1", "type": "string" },
              "datatype": "string"
            }
          ]
        },
        "qualifiers-order": ["P1545"],
        "id": "L4$faad30b0-421c-803a-c1fd-b9a99a0eb35d",
        "rank": "normal"
      },
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5238",
          "datavalue": {
            "value": {
              "entity-type": "lexeme",
              "numeric-id": 18537,
              "id": "L18537"
            },
            "type": "wikibase-entityid"
          },
          "datatype": "wikibase-lexeme"
        },
        "type": "statement",
        "qualifiers": {
          "P1545": [
            {
              "snaktype": "value",
              "property": "P1545",
              "hash": "7241753c62a310cf84895620ea82250dcea65835",
              "datavalue": { "value": "2", "type": "string" },
              "datatype": "string"
            }
          ]
        },
        "qualifiers-order": ["P1545"],
        "id": "L4$d15285a1-4880-7a9b-bb1f-85403e1a785a",
        "rank": "normal"
      }
    ],
    "P5187": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5187",
          "datavalue": {
            "value": { "text": "windsurf", "language": "en" },
            "type": "monolingualtext"
          },
          "datatype": "monolingualtext"
        },
        "type": "statement",
        "id": "L4$d4a63d17-43ea-749d-5860-21b90feb83f7",
        "rank": "normal"
      }
    ],
    "P5275": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5275",
          "datavalue": { "value": "229291", "type": "string" },
          "datatype": "external-id"
        },
        "type": "statement",
        "id": "L4$F82C77BF-4D4C-4020-8774-869AFC22C84F",
        "rank": "normal"
      }
    ]
  },
  "forms": [
    {
      "id": "L4-F1",
      "representations": { "en": { "language": "en", "value": "windsurfing" } },
      "grammaticalFeatures": ["Q10345583"],
      "claims": []
    },
    {
      "id": "L4-F3",
      "representations": { "en": { "language": "en", "value": "windsurfs" } },
      "grammaticalFeatures": ["Q110786", "Q3910936", "Q51929074"],
      "claims": []
    },
    {
      "id": "L4-F4",
      "representations": { "en": { "language": "en", "value": "windsurfed" } },
      "grammaticalFeatures": ["Q1392475"],
      "claims": []
    },
    {
      "id": "L4-F5",
      "representations": { "en": { "language": "en", "value": "windsurfed" } },
      "grammaticalFeatures": ["Q1230649"],
      "claims": []
    },
    {
      "id": "L4-F6",
      "representations": { "en": { "language": "en", "value": "windsurf" } },
      "grammaticalFeatures": ["Q3910936"],
      "claims": []
    }
  ],
  "senses": [
    {
      "id": "L4-S1",
      "glosses": {
        "fr": { "language": "fr", "value": "faire de la planche \u00e0 voile" },
        "ms": { "language": "ms", "value": "meluncur angin" },
        "zh": { "language": "zh", "value": "\u6ed1\u6d6a\u98a8\u5e06" },
        "zh-hant": {
          "language": "zh-hant",
          "value": "\u6ed1\u6d6a\u98a8\u5e06"
        },
        "zh-tw": { "language": "zh-tw", "value": "\u6ed1\u6d6a\u98a8\u5e06" },
        "nan": {
          "language": "nan",
          "value": "h\u00e1i-\u00edng hong-ph\u00e2ng"
        },
        "th": {
          "language": "th",
          "value": "\u0e40\u0e25\u0e48\u0e19\u0e27\u0e34\u0e19\u0e14\u0e4c\u0e40\u0e0b\u0e34\u0e23\u0e4c\u0e1f"
        },
        "tg": {
          "language": "tg",
          "value": "\u0441\u0451\u0440\u0444\u0438\u043d\u0433\u0431\u043e\u0437\u0438\u0438 \u0448\u0430\u043c\u043e\u043b\u04e3"
        },
        "fi": { "language": "fi", "value": "purjelautailla" }
      },
      "claims": {
        "P5137": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5137",
              "datavalue": {
                "value": {
                  "entity-type": "item",
                  "numeric-id": 191051,
                  "id": "Q191051"
                },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-item"
            },
            "type": "statement",
            "id": "L4-S1$13e5f498-4deb-ea41-4d60-02c852b88b4c",
            "rank": "normal"
          }
        ],
        "P5972": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5972",
              "datavalue": {
                "value": { "entity-type": "sense", "id": "L144039-S1" },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-sense"
            },
            "type": "statement",
            "id": "L4-S1$7218013F-B84B-40FA-B57B-BC1BA2239BB8",
            "rank": "normal"
          }
        ]
      }
    }
  ],
  "pageid": 54387040,
  "ns": 146,
  "title": "Lexeme:L4",
  "lastrevid": 1818218882,
  "modified": "2023-01-24T07:16:40Z"
}

=== josh/wikidata-api-schemas/test/lexeme/pass/L13.json
{
  "type": "lexeme",
  "id": "L13",
  "lemmas": { "en": { "language": "en", "value": "thirteen" } },
  "lexicalCategory": "Q63116",
  "language": "Q1860",
  "claims": {
    "P5402": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5402",
          "datavalue": {
            "value": {
              "entity-type": "lexeme",
              "numeric-id": 341159,
              "id": "L341159"
            },
            "type": "wikibase-entityid"
          },
          "datatype": "wikibase-lexeme"
        },
        "type": "statement",
        "id": "L13$DE99804E-ED7A-4432-9C74-1AAC56D6DBB7",
        "rank": "normal"
      },
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5402",
          "datavalue": {
            "value": {
              "entity-type": "lexeme",
              "numeric-id": 329263,
              "id": "L329263"
            },
            "type": "wikibase-entityid"
          },
          "datatype": "wikibase-lexeme"
        },
        "type": "statement",
        "id": "L13$A68A3662-FD38-43AE-80EE-B27A88AAFECC",
        "rank": "normal"
      }
    ]
  },
  "forms": [
    {
      "id": "L13-F1",
      "representations": { "en": { "language": "en", "value": "thirteen" } },
      "grammaticalFeatures": [],
      "claims": []
    }
  ],
  "senses": [
    {
      "id": "L13-S1",
      "glosses": {
        "ru": { "language": "ru", "value": "\u0447\u0438\u0441\u043b\u043e" },
        "fr": { "language": "fr", "value": "treize" },
        "ms": { "language": "ms", "value": "tiga belas" },
        "pl": { "language": "pl", "value": "trzyna\u015bcie" },
        "en": { "language": "en", "value": "number between 12 and 14" },
        "de": { "language": "de", "value": "dreizehn" },
        "zh": { "language": "zh", "value": "\u5341\u4e09" },
        "zh-hans": { "language": "zh-hans", "value": "\u5341\u4e09" },
        "it": { "language": "it", "value": "tredici" }
      },
      "claims": {
        "P5137": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5137",
              "datavalue": {
                "value": {
                  "entity-type": "item",
                  "numeric-id": 37141,
                  "id": "Q37141"
                },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-item"
            },
            "type": "statement",
            "id": "L13-S1$d9145183-4bbb-d177-b31e-949e457f6b51",
            "rank": "normal"
          }
        ],
        "P5972": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5972",
              "datavalue": {
                "value": { "entity-type": "sense", "id": "L230791-S1" },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-sense"
            },
            "type": "statement",
            "id": "L13-S1$fbc46459-44f6-fc88-9a8d-3e1dd40ed73e",
            "rank": "normal"
          }
        ]
      }
    }
  ],
  "pageid": 54387257,
  "ns": 146,
  "title": "Lexeme:L13",
  "lastrevid": 1908150558,
  "modified": "2023-06-04T17:08:59Z"
}

=== josh/wikidata-api-schemas/test/lexeme/pass/L9.json
{
  "type": "lexeme",
  "id": "L9",
  "lemmas": { "en": { "language": "en", "value": "create" } },
  "lexicalCategory": "Q24905",
  "language": "Q1860",
  "claims": {
    "P5831": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5831",
          "datavalue": {
            "value": {
              "text": "She creates artwork, to sell.",
              "language": "en"
            },
            "type": "monolingualtext"
          },
          "datatype": "monolingualtext"
        },
        "type": "statement",
        "qualifiers": {
          "P5830": [
            {
              "snaktype": "value",
              "property": "P5830",
              "hash": "9ff2cc8e32804edf1cbc77ef877e0ccfb670b594",
              "datavalue": {
                "value": { "entity-type": "form", "id": "L9-F1" },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-form"
            }
          ]
        },
        "qualifiers-order": ["P5830"],
        "id": "L9$ed422e09-44b2-7c15-47f6-efdd7a4dd853",
        "rank": "normal"
      }
    ],
    "P5191": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5191",
          "datavalue": {
            "value": {
              "entity-type": "lexeme",
              "numeric-id": 268592,
              "id": "L268592"
            },
            "type": "wikibase-entityid"
          },
          "datatype": "wikibase-lexeme"
        },
        "type": "statement",
        "id": "L9$bcbd7e19-4dc2-d8f4-de54-46440074f175",
        "rank": "normal"
      }
    ],
    "P5275": [
      {
        "mainsnak": {
          "snaktype": "value",
          "property": "P5275",
          "datavalue": { "value": "44061", "type": "string" },
          "datatype": "external-id"
        },
        "type": "statement",
        "id": "L9$5C5AF37A-7CF5-4D4B-82AE-FB09D3A4D3B3",
        "rank": "normal"
      }
    ]
  },
  "forms": [
    {
      "id": "L9-F1",
      "representations": { "en": { "language": "en", "value": "creates" } },
      "grammaticalFeatures": ["Q110786", "Q3910936", "Q51929074"],
      "claims": []
    },
    {
      "id": "L9-F2",
      "representations": { "en": { "language": "en", "value": "created" } },
      "grammaticalFeatures": ["Q1392475"],
      "claims": {
        "P443": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P443",
              "datavalue": { "value": "En-us-created.ogg", "type": "string" },
              "datatype": "commonsMedia"
            },
            "type": "statement",
            "id": "L9-F2$5538a029-4701-0368-7e91-50ecd9f5c2b6",
            "rank": "normal"
          }
        ]
      }
    },
    {
      "id": "L9-F3",
      "representations": { "en": { "language": "en", "value": "creating" } },
      "grammaticalFeatures": ["Q10345583"],
      "claims": {
        "P443": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P443",
              "datavalue": { "value": "En-us-creating.ogg", "type": "string" },
              "datatype": "commonsMedia"
            },
            "type": "statement",
            "id": "L9-F3$ed5a3baa-44fa-ee7a-2056-30ff0b4a30a3",
            "rank": "normal"
          }
        ]
      }
    },
    {
      "id": "L9-F4",
      "representations": { "en": { "language": "en", "value": "created" } },
      "grammaticalFeatures": ["Q1230649"],
      "claims": []
    },
    {
      "id": "L9-F5",
      "representations": { "en": { "language": "en", "value": "create" } },
      "grammaticalFeatures": ["Q3910936"],
      "claims": {
        "P443": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P443",
              "datavalue": { "value": "En-us-create.ogg", "type": "string" },
              "datatype": "commonsMedia"
            },
            "type": "statement",
            "id": "L9-F5$7872cdc0-4dfe-6652-c3cf-33ee033aed85",
            "rank": "normal"
          }
        ]
      }
    }
  ],
  "senses": [
    {
      "id": "L9-S1",
      "glosses": {
        "en": {
          "language": "en",
          "value": "make something new from other elements"
        },
        "de": {
          "language": "de",
          "value": "etwas Neues aus Bestehendem erschaffen"
        },
        "fr": {
          "language": "fr",
          "value": "fabriquer quelquechose \u00e0 partir d'autre \u00e9l\u00e9ments"
        },
        "es": {
          "language": "es",
          "value": "hacer algo nuevo o de otras cosas"
        },
        "th": { "language": "th", "value": "\u0e2a\u0e23\u0e49\u0e32\u0e07" },
        "it": { "language": "it", "value": "creare" }
      },
      "claims": {
        "P5972": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5972",
              "datavalue": {
                "value": { "entity-type": "sense", "id": "L230703-S1" },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-sense"
            },
            "type": "statement",
            "id": "L9-S1$1b26282c-426b-d63b-9194-654b86ff1629",
            "rank": "normal"
          }
        ]
      }
    },
    {
      "id": "L9-S2",
      "glosses": {
        "en": { "language": "en", "value": "bring into existence" },
        "fr": { "language": "fr", "value": "mener \u00e0 l'existence" },
        "de": { "language": "de", "value": "erzeugen" },
        "th": {
          "language": "th",
          "value": "\u0e19\u0e33\u0e44\u0e1b\u0e2a\u0e39\u0e48\u0e0b\u0e36\u0e48\u0e07\u0e01\u0e32\u0e23\u0e14\u0e33\u0e23\u0e07\u0e2d\u0e22\u0e39\u0e48"
        }
      },
      "claims": {
        "P11774": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P11774",
              "datavalue": { "value": "11320", "type": "string" },
              "datatype": "external-id"
            },
            "type": "statement",
            "id": "L9-S2$6f8ff693-4b8e-4842-d639-84eda39d68d6",
            "rank": "normal"
          }
        ]
      }
    },
    {
      "id": "L9-S3",
      "glosses": {
        "en": { "language": "en", "value": "make; cause to become" },
        "th": { "language": "th", "value": "\u0e17\u0e33" }
      },
      "claims": {
        "P5973": [
          {
            "mainsnak": {
              "snaktype": "value",
              "property": "P5973",
              "datavalue": {
                "value": { "entity-type": "sense", "id": "L3036-S4" },
                "type": "wikibase-entityid"
              },
              "datatype": "wikibase-sense"
            },
            "type": "statement",
            "id": "L9-S3$5db22788-4db7-d9eb-4278-4ca396cfbdbf",
            "rank": "normal"
          }
        ]
      }
    },
    {
      "id": "L9-S4",
      "glosses": {
        "en": {
          "language": "en",
          "value": "create or manufacture a man-made product"
        },
        "fr": {
          "language": "fr",
          "value": "cr\u00e9er ou fabriquer un produit de main humaine"
        }
      },
      "claims": []
    }
  ],
  "pageid": 54387147,
  "ns": 146,
  "title": "Lexeme:L9",
  "lastrevid": 1902626745,
  "modified": "2023-05-25T17:24:54Z"
}

=== josh/wikidata-api-schemas/test/lexeme/pass/L68.json
{
  "type": "lexeme",
  "id": "L68",
  "lemmas": {
    "fa": { "language": "fa", "value": "\u062c\u0627\u0646\u0627\u0646" }
  },
  "lexicalCategory": "Q34698",
  "language": "Q9168",
  "claims": {},
  "forms": {},
  "senses": [
    {
      "id": "L68-S1",
      "glosses": {
        "fa": {
          "language": "fa",
          "value": "\u0645\u0639\u0634\u0648\u0642\u060c \u0645\u062d\u0628\u0648\u0628"
        }
      },
      "claims": []
    }
  ],
  "pageid": 54387656,
  "ns": 146,
  "title": "Lexeme:L68",
  "lastrevid": 1804327696,
  "modified": "2023-01-06T02:45:33Z"
}
